In [3]:
import numpy as np
from astropy import constants
from astropy import units as u

In [49]:
ML = 1.0 * u.M_sun.to('kg')  # Stellar mass host star 
ML = 10.0 * u.M_sun.to('kg')  # Compact object host star
DL = 4000.0 * u.pc.to('m')
DLS = 4000.0 * u.pc.to('m')
DS = DL+DLS

mu = 1.0 + (DL/DLS)
D = (DL*DLS)/DS

nu = 200.0 * 1000.0 * u.m.to('m')/u.s.to('s')

Microlensing events have a characteristic angular Einstein radius, defined as:

In [50]:
thetaE = np.sqrt( (4.0 * constants.G.value * ML)/(mu*DL*constants.c.value*constants.c.value) )
RE = np.sqrt( (4.0 * constants.G.value * ML * D)/(constants.c.value*constants.c.value) )
print('Angular Einstein radius = '+str(thetaE))
print('Einstein radius = '+str(RE)+'m')

Angular Einstein radius = 1.5468380396130428e-08
Einstein radius = 1909217384412.8086m


Stars in the Milky Way typically have velocities around 100 km/s.   We use an estimated relative rate of transverse motion

The characteristic timescale of a microlensing event is given by the time the lens takes to cross the source

In [51]:
tE = RE / nu
print('Einstein crossing time, tE: '+str(tE)+'s')
print('Einstein crossing time, tE: '+str(tE/(60.0*60.0*24.0))+'days')

Einstein crossing time, tE: 9546086.922064044s
Einstein crossing time, tE: 110.48711715351902days


Typical angular sizes of lenses

In [56]:
Rlens = 100*u.R_sun.to('m')
thetaL = np.tan(Rlens / DS)
print(thetaL/thetaE)

0.018219507261976006


In [62]:
ts = np.arange(0,10,1)
ts2 = np.arange(10,100,10)
tt1,tt2 = np.meshgrid(ts,ts2)
print(tt1)
print(tt2)
print(tt2-tt1)

[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]
[[10 10 10 10 10 10 10 10 10 10]
 [20 20 20 20 20 20 20 20 20 20]
 [30 30 30 30 30 30 30 30 30 30]
 [40 40 40 40 40 40 40 40 40 40]
 [50 50 50 50 50 50 50 50 50 50]
 [60 60 60 60 60 60 60 60 60 60]
 [70 70 70 70 70 70 70 70 70 70]
 [80 80 80 80 80 80 80 80 80 80]
 [90 90 90 90 90 90 90 90 90 90]]
[[10  9  8  7  6  5  4  3  2  1]
 [20 19 18 17 16 15 14 13 12 11]
 [30 29 28 27 26 25 24 23 22 21]
 [40 39 38 37 36 35 34 33 32 31]
 [50 49 48 47 46 45 44 43 42 41]
 [60 59 58 57 56 55 54 53 52 51]
 [70 69 68 67 66 65 64 63 62 61]
 [80 79 78 77 76 75 74 73 72 71]
 [90 89 88 87 86 85 84 83 82 81]]


In [63]:
idx = np.where((tt2-tt1) > 35)
print(idx)

(array([3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8]), array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6,
       7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8,
       9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))
